# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/compiler/CMakeFiles /home/compiler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named printast

# Build rule for target.
printast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 printast
.PHONY : printast

# fast build rule for target.
printast/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/build
.PHONY : printast/fast

#=============================================================================
# Target rules for targets named irgen

# Build rule for target.
irgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irgen
.PHONY : irgen

# fast build rule for target.
irgen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/build
.PHONY : irgen/fast

#=============================================================================
# Target rules for targets named printir

# Build rule for target.
printir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 printir
.PHONY : printir

# fast build rule for target.
printir/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/build
.PHONY : printir/fast

#=============================================================================
# Target rules for targets named asmgen

# Build rule for target.
asmgen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asmgen
.PHONY : asmgen

# fast build rule for target.
asmgen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/build
.PHONY : asmgen/fast

debug/asmgen.o: debug/asmgen.cpp.o
.PHONY : debug/asmgen.o

# target to build an object file
debug/asmgen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/debug/asmgen.cpp.o
.PHONY : debug/asmgen.cpp.o

debug/asmgen.i: debug/asmgen.cpp.i
.PHONY : debug/asmgen.i

# target to preprocess a source file
debug/asmgen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/debug/asmgen.cpp.i
.PHONY : debug/asmgen.cpp.i

debug/asmgen.s: debug/asmgen.cpp.s
.PHONY : debug/asmgen.s

# target to generate assembly for a file
debug/asmgen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/debug/asmgen.cpp.s
.PHONY : debug/asmgen.cpp.s

debug/irgen.o: debug/irgen.cpp.o
.PHONY : debug/irgen.o

# target to build an object file
debug/irgen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/debug/irgen.cpp.o
.PHONY : debug/irgen.cpp.o

debug/irgen.i: debug/irgen.cpp.i
.PHONY : debug/irgen.i

# target to preprocess a source file
debug/irgen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/debug/irgen.cpp.i
.PHONY : debug/irgen.cpp.i

debug/irgen.s: debug/irgen.cpp.s
.PHONY : debug/irgen.s

# target to generate assembly for a file
debug/irgen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/debug/irgen.cpp.s
.PHONY : debug/irgen.cpp.s

debug/irprintertest.o: debug/irprintertest.cpp.o
.PHONY : debug/irprintertest.o

# target to build an object file
debug/irprintertest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/debug/irprintertest.cpp.o
.PHONY : debug/irprintertest.cpp.o

debug/irprintertest.i: debug/irprintertest.cpp.i
.PHONY : debug/irprintertest.i

# target to preprocess a source file
debug/irprintertest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/debug/irprintertest.cpp.i
.PHONY : debug/irprintertest.cpp.i

debug/irprintertest.s: debug/irprintertest.cpp.s
.PHONY : debug/irprintertest.s

# target to generate assembly for a file
debug/irprintertest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/debug/irprintertest.cpp.s
.PHONY : debug/irprintertest.cpp.s

debug/printast.o: debug/printast.cpp.o
.PHONY : debug/printast.o

# target to build an object file
debug/printast.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/debug/printast.cpp.o
.PHONY : debug/printast.cpp.o

debug/printast.i: debug/printast.cpp.i
.PHONY : debug/printast.i

# target to preprocess a source file
debug/printast.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/debug/printast.cpp.i
.PHONY : debug/printast.cpp.i

debug/printast.s: debug/printast.cpp.s
.PHONY : debug/printast.s

# target to generate assembly for a file
debug/printast.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/debug/printast.cpp.s
.PHONY : debug/printast.cpp.s

lib/ir/base.o: lib/ir/base.cpp.o
.PHONY : lib/ir/base.o

# target to build an object file
lib/ir/base.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/base.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/base.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/base.cpp.o
.PHONY : lib/ir/base.cpp.o

lib/ir/base.i: lib/ir/base.cpp.i
.PHONY : lib/ir/base.i

# target to preprocess a source file
lib/ir/base.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/base.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/base.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/base.cpp.i
.PHONY : lib/ir/base.cpp.i

lib/ir/base.s: lib/ir/base.cpp.s
.PHONY : lib/ir/base.s

# target to generate assembly for a file
lib/ir/base.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/base.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/base.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/base.cpp.s
.PHONY : lib/ir/base.cpp.s

lib/ir/basic_block.o: lib/ir/basic_block.cpp.o
.PHONY : lib/ir/basic_block.o

# target to build an object file
lib/ir/basic_block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/basic_block.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/basic_block.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/basic_block.cpp.o
.PHONY : lib/ir/basic_block.cpp.o

lib/ir/basic_block.i: lib/ir/basic_block.cpp.i
.PHONY : lib/ir/basic_block.i

# target to preprocess a source file
lib/ir/basic_block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/basic_block.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/basic_block.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/basic_block.cpp.i
.PHONY : lib/ir/basic_block.cpp.i

lib/ir/basic_block.s: lib/ir/basic_block.cpp.s
.PHONY : lib/ir/basic_block.s

# target to generate assembly for a file
lib/ir/basic_block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/basic_block.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/basic_block.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/basic_block.cpp.s
.PHONY : lib/ir/basic_block.cpp.s

lib/ir/constant.o: lib/ir/constant.cpp.o
.PHONY : lib/ir/constant.o

# target to build an object file
lib/ir/constant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/constant.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/constant.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/constant.cpp.o
.PHONY : lib/ir/constant.cpp.o

lib/ir/constant.i: lib/ir/constant.cpp.i
.PHONY : lib/ir/constant.i

# target to preprocess a source file
lib/ir/constant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/constant.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/constant.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/constant.cpp.i
.PHONY : lib/ir/constant.cpp.i

lib/ir/constant.s: lib/ir/constant.cpp.s
.PHONY : lib/ir/constant.s

# target to generate assembly for a file
lib/ir/constant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/constant.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/constant.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/constant.cpp.s
.PHONY : lib/ir/constant.cpp.s

lib/ir/constantpool.o: lib/ir/constantpool.cpp.o
.PHONY : lib/ir/constantpool.o

# target to build an object file
lib/ir/constantpool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/constantpool.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/constantpool.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/constantpool.cpp.o
.PHONY : lib/ir/constantpool.cpp.o

lib/ir/constantpool.i: lib/ir/constantpool.cpp.i
.PHONY : lib/ir/constantpool.i

# target to preprocess a source file
lib/ir/constantpool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/constantpool.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/constantpool.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/constantpool.cpp.i
.PHONY : lib/ir/constantpool.cpp.i

lib/ir/constantpool.s: lib/ir/constantpool.cpp.s
.PHONY : lib/ir/constantpool.s

# target to generate assembly for a file
lib/ir/constantpool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/constantpool.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/constantpool.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/constantpool.cpp.s
.PHONY : lib/ir/constantpool.cpp.s

lib/ir/function.o: lib/ir/function.cpp.o
.PHONY : lib/ir/function.o

# target to build an object file
lib/ir/function.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/function.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/function.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/function.cpp.o
.PHONY : lib/ir/function.cpp.o

lib/ir/function.i: lib/ir/function.cpp.i
.PHONY : lib/ir/function.i

# target to preprocess a source file
lib/ir/function.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/function.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/function.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/function.cpp.i
.PHONY : lib/ir/function.cpp.i

lib/ir/function.s: lib/ir/function.cpp.s
.PHONY : lib/ir/function.s

# target to generate assembly for a file
lib/ir/function.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/function.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/function.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/function.cpp.s
.PHONY : lib/ir/function.cpp.s

lib/ir/global_var.o: lib/ir/global_var.cpp.o
.PHONY : lib/ir/global_var.o

# target to build an object file
lib/ir/global_var.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/global_var.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/global_var.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/global_var.cpp.o
.PHONY : lib/ir/global_var.cpp.o

lib/ir/global_var.i: lib/ir/global_var.cpp.i
.PHONY : lib/ir/global_var.i

# target to preprocess a source file
lib/ir/global_var.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/global_var.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/global_var.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/global_var.cpp.i
.PHONY : lib/ir/global_var.cpp.i

lib/ir/global_var.s: lib/ir/global_var.cpp.s
.PHONY : lib/ir/global_var.s

# target to generate assembly for a file
lib/ir/global_var.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/global_var.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/global_var.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/global_var.cpp.s
.PHONY : lib/ir/global_var.cpp.s

lib/ir/instruction.o: lib/ir/instruction.cpp.o
.PHONY : lib/ir/instruction.o

# target to build an object file
lib/ir/instruction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instruction.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instruction.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instruction.cpp.o
.PHONY : lib/ir/instruction.cpp.o

lib/ir/instruction.i: lib/ir/instruction.cpp.i
.PHONY : lib/ir/instruction.i

# target to preprocess a source file
lib/ir/instruction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instruction.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instruction.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instruction.cpp.i
.PHONY : lib/ir/instruction.cpp.i

lib/ir/instruction.s: lib/ir/instruction.cpp.s
.PHONY : lib/ir/instruction.s

# target to generate assembly for a file
lib/ir/instruction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instruction.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instruction.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instruction.cpp.s
.PHONY : lib/ir/instruction.cpp.s

lib/ir/instructions/binary.o: lib/ir/instructions/binary.cpp.o
.PHONY : lib/ir/instructions/binary.o

# target to build an object file
lib/ir/instructions/binary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/binary.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/binary.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/binary.cpp.o
.PHONY : lib/ir/instructions/binary.cpp.o

lib/ir/instructions/binary.i: lib/ir/instructions/binary.cpp.i
.PHONY : lib/ir/instructions/binary.i

# target to preprocess a source file
lib/ir/instructions/binary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/binary.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/binary.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/binary.cpp.i
.PHONY : lib/ir/instructions/binary.cpp.i

lib/ir/instructions/binary.s: lib/ir/instructions/binary.cpp.s
.PHONY : lib/ir/instructions/binary.s

# target to generate assembly for a file
lib/ir/instructions/binary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/binary.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/binary.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/binary.cpp.s
.PHONY : lib/ir/instructions/binary.cpp.s

lib/ir/instructions/compare.o: lib/ir/instructions/compare.cpp.o
.PHONY : lib/ir/instructions/compare.o

# target to build an object file
lib/ir/instructions/compare.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/compare.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/compare.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/compare.cpp.o
.PHONY : lib/ir/instructions/compare.cpp.o

lib/ir/instructions/compare.i: lib/ir/instructions/compare.cpp.i
.PHONY : lib/ir/instructions/compare.i

# target to preprocess a source file
lib/ir/instructions/compare.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/compare.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/compare.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/compare.cpp.i
.PHONY : lib/ir/instructions/compare.cpp.i

lib/ir/instructions/compare.s: lib/ir/instructions/compare.cpp.s
.PHONY : lib/ir/instructions/compare.s

# target to generate assembly for a file
lib/ir/instructions/compare.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/compare.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/compare.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/compare.cpp.s
.PHONY : lib/ir/instructions/compare.cpp.s

lib/ir/instructions/control.o: lib/ir/instructions/control.cpp.o
.PHONY : lib/ir/instructions/control.o

# target to build an object file
lib/ir/instructions/control.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/control.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/control.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/control.cpp.o
.PHONY : lib/ir/instructions/control.cpp.o

lib/ir/instructions/control.i: lib/ir/instructions/control.cpp.i
.PHONY : lib/ir/instructions/control.i

# target to preprocess a source file
lib/ir/instructions/control.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/control.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/control.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/control.cpp.i
.PHONY : lib/ir/instructions/control.cpp.i

lib/ir/instructions/control.s: lib/ir/instructions/control.cpp.s
.PHONY : lib/ir/instructions/control.s

# target to generate assembly for a file
lib/ir/instructions/control.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/control.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/control.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/control.cpp.s
.PHONY : lib/ir/instructions/control.cpp.s

lib/ir/instructions/converse.o: lib/ir/instructions/converse.cpp.o
.PHONY : lib/ir/instructions/converse.o

# target to build an object file
lib/ir/instructions/converse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/converse.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/converse.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/converse.cpp.o
.PHONY : lib/ir/instructions/converse.cpp.o

lib/ir/instructions/converse.i: lib/ir/instructions/converse.cpp.i
.PHONY : lib/ir/instructions/converse.i

# target to preprocess a source file
lib/ir/instructions/converse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/converse.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/converse.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/converse.cpp.i
.PHONY : lib/ir/instructions/converse.cpp.i

lib/ir/instructions/converse.s: lib/ir/instructions/converse.cpp.s
.PHONY : lib/ir/instructions/converse.s

# target to generate assembly for a file
lib/ir/instructions/converse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/converse.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/converse.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/converse.cpp.s
.PHONY : lib/ir/instructions/converse.cpp.s

lib/ir/instructions/helper.o: lib/ir/instructions/helper.cpp.o
.PHONY : lib/ir/instructions/helper.o

# target to build an object file
lib/ir/instructions/helper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/helper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/helper.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/helper.cpp.o
.PHONY : lib/ir/instructions/helper.cpp.o

lib/ir/instructions/helper.i: lib/ir/instructions/helper.cpp.i
.PHONY : lib/ir/instructions/helper.i

# target to preprocess a source file
lib/ir/instructions/helper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/helper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/helper.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/helper.cpp.i
.PHONY : lib/ir/instructions/helper.cpp.i

lib/ir/instructions/helper.s: lib/ir/instructions/helper.cpp.s
.PHONY : lib/ir/instructions/helper.s

# target to generate assembly for a file
lib/ir/instructions/helper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/helper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/helper.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/helper.cpp.s
.PHONY : lib/ir/instructions/helper.cpp.s

lib/ir/instructions/memory.o: lib/ir/instructions/memory.cpp.o
.PHONY : lib/ir/instructions/memory.o

# target to build an object file
lib/ir/instructions/memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/memory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/memory.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/memory.cpp.o
.PHONY : lib/ir/instructions/memory.cpp.o

lib/ir/instructions/memory.i: lib/ir/instructions/memory.cpp.i
.PHONY : lib/ir/instructions/memory.i

# target to preprocess a source file
lib/ir/instructions/memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/memory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/memory.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/memory.cpp.i
.PHONY : lib/ir/instructions/memory.cpp.i

lib/ir/instructions/memory.s: lib/ir/instructions/memory.cpp.s
.PHONY : lib/ir/instructions/memory.s

# target to generate assembly for a file
lib/ir/instructions/memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/memory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/memory.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/memory.cpp.s
.PHONY : lib/ir/instructions/memory.cpp.s

lib/ir/instructions/phi.o: lib/ir/instructions/phi.cpp.o
.PHONY : lib/ir/instructions/phi.o

# target to build an object file
lib/ir/instructions/phi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/phi.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/phi.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/phi.cpp.o
.PHONY : lib/ir/instructions/phi.cpp.o

lib/ir/instructions/phi.i: lib/ir/instructions/phi.cpp.i
.PHONY : lib/ir/instructions/phi.i

# target to preprocess a source file
lib/ir/instructions/phi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/phi.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/phi.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/phi.cpp.i
.PHONY : lib/ir/instructions/phi.cpp.i

lib/ir/instructions/phi.s: lib/ir/instructions/phi.cpp.s
.PHONY : lib/ir/instructions/phi.s

# target to generate assembly for a file
lib/ir/instructions/phi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/instructions/phi.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/instructions/phi.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/instructions/phi.cpp.s
.PHONY : lib/ir/instructions/phi.cpp.s

lib/ir/module.o: lib/ir/module.cpp.o
.PHONY : lib/ir/module.o

# target to build an object file
lib/ir/module.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/module.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/module.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/module.cpp.o
.PHONY : lib/ir/module.cpp.o

lib/ir/module.i: lib/ir/module.cpp.i
.PHONY : lib/ir/module.i

# target to preprocess a source file
lib/ir/module.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/module.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/module.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/module.cpp.i
.PHONY : lib/ir/module.cpp.i

lib/ir/module.s: lib/ir/module.cpp.s
.PHONY : lib/ir/module.s

# target to generate assembly for a file
lib/ir/module.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/module.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/module.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/module.cpp.s
.PHONY : lib/ir/module.cpp.s

lib/ir/type.o: lib/ir/type.cpp.o
.PHONY : lib/ir/type.o

# target to build an object file
lib/ir/type.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/type.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/type.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/type.cpp.o
.PHONY : lib/ir/type.cpp.o

lib/ir/type.i: lib/ir/type.cpp.i
.PHONY : lib/ir/type.i

# target to preprocess a source file
lib/ir/type.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/type.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/type.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/type.cpp.i
.PHONY : lib/ir/type.cpp.i

lib/ir/type.s: lib/ir/type.cpp.s
.PHONY : lib/ir/type.s

# target to generate assembly for a file
lib/ir/type.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/type.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/type.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/type.cpp.s
.PHONY : lib/ir/type.cpp.s

lib/ir/utilities.o: lib/ir/utilities.cpp.o
.PHONY : lib/ir/utilities.o

# target to build an object file
lib/ir/utilities.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/utilities.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/utilities.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/utilities.cpp.o
.PHONY : lib/ir/utilities.cpp.o

lib/ir/utilities.i: lib/ir/utilities.cpp.i
.PHONY : lib/ir/utilities.i

# target to preprocess a source file
lib/ir/utilities.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/utilities.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/utilities.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/utilities.cpp.i
.PHONY : lib/ir/utilities.cpp.i

lib/ir/utilities.s: lib/ir/utilities.cpp.s
.PHONY : lib/ir/utilities.s

# target to generate assembly for a file
lib/ir/utilities.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/ir/utilities.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/ir/utilities.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/asmgen.dir/build.make CMakeFiles/asmgen.dir/lib/ir/utilities.cpp.s
.PHONY : lib/ir/utilities.cpp.s

lib/irvisitors/irprinter.o: lib/irvisitors/irprinter.cpp.o
.PHONY : lib/irvisitors/irprinter.o

# target to build an object file
lib/irvisitors/irprinter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/irvisitors/irprinter.cpp.o
.PHONY : lib/irvisitors/irprinter.cpp.o

lib/irvisitors/irprinter.i: lib/irvisitors/irprinter.cpp.i
.PHONY : lib/irvisitors/irprinter.i

# target to preprocess a source file
lib/irvisitors/irprinter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/irvisitors/irprinter.cpp.i
.PHONY : lib/irvisitors/irprinter.cpp.i

lib/irvisitors/irprinter.s: lib/irvisitors/irprinter.cpp.s
.PHONY : lib/irvisitors/irprinter.s

# target to generate assembly for a file
lib/irvisitors/irprinter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/irvisitors/irprinter.cpp.s
.PHONY : lib/irvisitors/irprinter.cpp.s

lib/lexer/lexer.o: lib/lexer/lexer.cpp.o
.PHONY : lib/lexer/lexer.o

# target to build an object file
lib/lexer/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/lib/lexer/lexer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/lexer/lexer.cpp.o
.PHONY : lib/lexer/lexer.cpp.o

lib/lexer/lexer.i: lib/lexer/lexer.cpp.i
.PHONY : lib/lexer/lexer.i

# target to preprocess a source file
lib/lexer/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/lib/lexer/lexer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/lexer/lexer.cpp.i
.PHONY : lib/lexer/lexer.cpp.i

lib/lexer/lexer.s: lib/lexer/lexer.cpp.s
.PHONY : lib/lexer/lexer.s

# target to generate assembly for a file
lib/lexer/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/lib/lexer/lexer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/lexer/lexer.cpp.s
.PHONY : lib/lexer/lexer.cpp.s

lib/parser/ast_printer.o: lib/parser/ast_printer.cpp.o
.PHONY : lib/parser/ast_printer.o

# target to build an object file
lib/parser/ast_printer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/lib/parser/ast_printer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/parser/ast_printer.cpp.o
.PHONY : lib/parser/ast_printer.cpp.o

lib/parser/ast_printer.i: lib/parser/ast_printer.cpp.i
.PHONY : lib/parser/ast_printer.i

# target to preprocess a source file
lib/parser/ast_printer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/lib/parser/ast_printer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/parser/ast_printer.cpp.i
.PHONY : lib/parser/ast_printer.cpp.i

lib/parser/ast_printer.s: lib/parser/ast_printer.cpp.s
.PHONY : lib/parser/ast_printer.s

# target to generate assembly for a file
lib/parser/ast_printer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/lib/parser/ast_printer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/parser/ast_printer.cpp.s
.PHONY : lib/parser/ast_printer.cpp.s

lib/parser/irgen.o: lib/parser/irgen.cpp.o
.PHONY : lib/parser/irgen.o

# target to build an object file
lib/parser/irgen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/parser/irgen.cpp.o
.PHONY : lib/parser/irgen.cpp.o

lib/parser/irgen.i: lib/parser/irgen.cpp.i
.PHONY : lib/parser/irgen.i

# target to preprocess a source file
lib/parser/irgen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/parser/irgen.cpp.i
.PHONY : lib/parser/irgen.cpp.i

lib/parser/irgen.s: lib/parser/irgen.cpp.s
.PHONY : lib/parser/irgen.s

# target to generate assembly for a file
lib/parser/irgen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/parser/irgen.cpp.s
.PHONY : lib/parser/irgen.cpp.s

lib/parser/parser.o: lib/parser/parser.cpp.o
.PHONY : lib/parser/parser.o

# target to build an object file
lib/parser/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/lib/parser/parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/parser/parser.cpp.o
.PHONY : lib/parser/parser.cpp.o

lib/parser/parser.i: lib/parser/parser.cpp.i
.PHONY : lib/parser/parser.i

# target to preprocess a source file
lib/parser/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/lib/parser/parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/parser/parser.cpp.i
.PHONY : lib/parser/parser.cpp.i

lib/parser/parser.s: lib/parser/parser.cpp.s
.PHONY : lib/parser/parser.s

# target to generate assembly for a file
lib/parser/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printast.dir/build.make CMakeFiles/printast.dir/lib/parser/parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/parser/parser.cpp.s
.PHONY : lib/parser/parser.cpp.s

lib/utils/logger.o: lib/utils/logger.cpp.o
.PHONY : lib/utils/logger.o

# target to build an object file
lib/utils/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/utils/logger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/utils/logger.cpp.o
.PHONY : lib/utils/logger.cpp.o

lib/utils/logger.i: lib/utils/logger.cpp.i
.PHONY : lib/utils/logger.i

# target to preprocess a source file
lib/utils/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/utils/logger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/utils/logger.cpp.i
.PHONY : lib/utils/logger.cpp.i

lib/utils/logger.s: lib/utils/logger.cpp.s
.PHONY : lib/utils/logger.s

# target to generate assembly for a file
lib/utils/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/irgen.dir/build.make CMakeFiles/irgen.dir/lib/utils/logger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/printir.dir/build.make CMakeFiles/printir.dir/lib/utils/logger.cpp.s
.PHONY : lib/utils/logger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... asmgen"
	@echo "... irgen"
	@echo "... printast"
	@echo "... printir"
	@echo "... debug/asmgen.o"
	@echo "... debug/asmgen.i"
	@echo "... debug/asmgen.s"
	@echo "... debug/irgen.o"
	@echo "... debug/irgen.i"
	@echo "... debug/irgen.s"
	@echo "... debug/irprintertest.o"
	@echo "... debug/irprintertest.i"
	@echo "... debug/irprintertest.s"
	@echo "... debug/printast.o"
	@echo "... debug/printast.i"
	@echo "... debug/printast.s"
	@echo "... lib/ir/base.o"
	@echo "... lib/ir/base.i"
	@echo "... lib/ir/base.s"
	@echo "... lib/ir/basic_block.o"
	@echo "... lib/ir/basic_block.i"
	@echo "... lib/ir/basic_block.s"
	@echo "... lib/ir/constant.o"
	@echo "... lib/ir/constant.i"
	@echo "... lib/ir/constant.s"
	@echo "... lib/ir/constantpool.o"
	@echo "... lib/ir/constantpool.i"
	@echo "... lib/ir/constantpool.s"
	@echo "... lib/ir/function.o"
	@echo "... lib/ir/function.i"
	@echo "... lib/ir/function.s"
	@echo "... lib/ir/global_var.o"
	@echo "... lib/ir/global_var.i"
	@echo "... lib/ir/global_var.s"
	@echo "... lib/ir/instruction.o"
	@echo "... lib/ir/instruction.i"
	@echo "... lib/ir/instruction.s"
	@echo "... lib/ir/instructions/binary.o"
	@echo "... lib/ir/instructions/binary.i"
	@echo "... lib/ir/instructions/binary.s"
	@echo "... lib/ir/instructions/compare.o"
	@echo "... lib/ir/instructions/compare.i"
	@echo "... lib/ir/instructions/compare.s"
	@echo "... lib/ir/instructions/control.o"
	@echo "... lib/ir/instructions/control.i"
	@echo "... lib/ir/instructions/control.s"
	@echo "... lib/ir/instructions/converse.o"
	@echo "... lib/ir/instructions/converse.i"
	@echo "... lib/ir/instructions/converse.s"
	@echo "... lib/ir/instructions/helper.o"
	@echo "... lib/ir/instructions/helper.i"
	@echo "... lib/ir/instructions/helper.s"
	@echo "... lib/ir/instructions/memory.o"
	@echo "... lib/ir/instructions/memory.i"
	@echo "... lib/ir/instructions/memory.s"
	@echo "... lib/ir/instructions/phi.o"
	@echo "... lib/ir/instructions/phi.i"
	@echo "... lib/ir/instructions/phi.s"
	@echo "... lib/ir/module.o"
	@echo "... lib/ir/module.i"
	@echo "... lib/ir/module.s"
	@echo "... lib/ir/type.o"
	@echo "... lib/ir/type.i"
	@echo "... lib/ir/type.s"
	@echo "... lib/ir/utilities.o"
	@echo "... lib/ir/utilities.i"
	@echo "... lib/ir/utilities.s"
	@echo "... lib/irvisitors/irprinter.o"
	@echo "... lib/irvisitors/irprinter.i"
	@echo "... lib/irvisitors/irprinter.s"
	@echo "... lib/lexer/lexer.o"
	@echo "... lib/lexer/lexer.i"
	@echo "... lib/lexer/lexer.s"
	@echo "... lib/parser/ast_printer.o"
	@echo "... lib/parser/ast_printer.i"
	@echo "... lib/parser/ast_printer.s"
	@echo "... lib/parser/irgen.o"
	@echo "... lib/parser/irgen.i"
	@echo "... lib/parser/irgen.s"
	@echo "... lib/parser/parser.o"
	@echo "... lib/parser/parser.i"
	@echo "... lib/parser/parser.s"
	@echo "... lib/utils/logger.o"
	@echo "... lib/utils/logger.i"
	@echo "... lib/utils/logger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

