#line 2 "irlexer.cpp"

#line 4 "irlexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[275] =
    {   0,
        0,    0,   80,   78,    2,    2,   78,    4,   70,   71,
       66,   78,   76,   78,   78,    5,    5,    1,   77,   74,
       75,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   67,   78,
       72,   73,    3,    0,    0,    3,    4,    0,    5,    5,
        0,    5,    5,    0,    8,    8,    6,    0,    0,    0,
        5,    1,    1,    0,    0,    0,    0,   12,    0,    0,
        0,    0,   48,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   61,    0,   62,    0,    0,    0,
        0,   49,    0,    0,    0,    0,    0,   25,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   47,    0,
        0,    8,    8,    0,    0,    5,   69,    0,    8,    0,
        0,    9,    0,    7,   14,    0,    0,   24,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   63,    0,    0,    0,   18,
        0,   54,   56,   55,   58,   57,   59,   60,   36,   11,
        0,   51,   50,    0,   53,   52,    0,    0,   16,    0,
        0,    0,    0,    0,    8,    0,    9,    0,    0,    8,
        0,    0,    0,    0,    0,    0,   37,    0,    0,    0,
        0,   15,   35,   21,    0,   19,   13,    0,   23,   17,

        0,    0,   34,    0,   27,    0,   20,    0,   22,    0,
       46,   65,    0,   32,    0,    8,    0,    0,    0,   10,
       43,    0,    0,    0,    0,    0,    0,   64,    0,    0,
        0,   45,    0,    0,   28,    0,   10,   26,    0,    0,
        0,   38,    0,   30,    0,   41,    0,   31,    0,   33,
        0,   39,    0,    0,   44,    0,   42,    0,    0,    0,
       40,    0,    0,    0,    0,    0,    0,    0,    0,   29,
        0,    0,   68,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    4,    5,    1,    1,    6,
        7,    8,    9,   10,   11,   12,    1,   13,   14,   15,
       16,   17,   17,   17,   17,   18,   19,   20,   21,    1,
       22,    1,    1,    5,   23,   23,   23,   23,   24,   23,
        4,    4,    4,    4,    4,    4,    4,    4,    4,   25,
        4,    4,    4,    4,    4,    4,    4,   26,    4,    4,
       27,    1,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,    4,    4,   39,   40,   41,
       42,   43,   44,   45,   46,   47,   48,   49,    4,   50,
        4,   51,   52,    1,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[54] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    4,    1,
        5,    6,    7,    7,    7,    7,    7,    7,    7,    8,
        1,    1,    3,    9,    3,    3,    1,    1,    3,    3,
        3,    3,    3,    9,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1
    } ;

static const flex_int16_t yy_base[286] =
    {   0,
        0,    0,  238,  205,  180, 1420,   53,  174,  167,  166,
      165,   44,  158,  106,  148,  156,  194,  136,  134,  132,
      123,  233,   38,   52,   56,   59,  245,   96,  163,  106,
      105,  150,  182,  160,  116,  259,  189,   45,  193,  202,
      112,   97, 1420,   90,  220,   84,   81,  295,  164,  205,
      303,  310,  349,  221,  372,  395,   46,  418,  444,  452,
      475,    0,    0,  224,  296,  240,  299,  260,  300,  309,
      312,  316,  336,  337,  341,  359,  360,  406,  382,  463,
      407,  464,  467,  385,  410,  480,  439,  476,  487,  494,
      440,  490,  497,  507,  508,  519,  523,  526,  530,  537,

      541,  552,  542,  561,  564,  568,  573,  578,  582,  587,
      591,   75,  107,  246,   56,  510,  594,  633,  641,  131,
      664,  672,  680,  212,  598,  628,  629,  633,  668,  683,
      684,  687,  694,  705,  698,  708,  709,  722,  721,  731,
      732,  736,  747,  748,  752,  751,  761,  762,  766,  773,
      776,  777,  780,  787,  790,  791,  794,  801,  804,  805,
      808,  815,  819,  820,  830,  831,  834,  843,  844,  848,
      853,  857,  862,   57,  370,  897,  904,  194,  912,  920,
       45,  927,  962,  867,  915,  952,  951,  955,  956,  965,
      966,  970,  975,  979,  980,  984,  989,  993,  996, 1003,

     1007, 1008, 1012, 1017, 1021, 1022, 1026, 1031, 1035, 1044,
     1040, 1047, 1051, 1054,  950, 1083,    0,   49, 1091, 1099,
     1086, 1090, 1089, 1103, 1093, 1106, 1110, 1115, 1120, 1129,
     1132, 1133, 1142, 1145, 1146, 1156, 1185, 1172, 1173, 1176,
     1185, 1188, 1198, 1195, 1202, 1199, 1211, 1212, 1216, 1223,
     1226, 1227, 1239, 1242, 1238, 1249, 1252, 1253, 1256, 1265,
     1266, 1269, 1279, 1278, 1289, 1290, 1294, 1301, 1306, 1310,
     1319, 1322, 1315, 1420, 1367, 1374, 1378, 1386, 1390, 1394,
     1397, 1400, 1406, 1410, 1411
    } ;

static const flex_int16_t yy_def[286] =
    {   0,
      274,    1,  274,  274,  274,  274,  275,  276,  274,  274,
      274,  277,  274,  275,   14,   14,   16,  278,  274,  274,
      274,   14,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
      274,  274,  274,  274,   22,  274,  276,  274,  279,  280,
       14,   16,   14,   22,   14,   14,   16,   14,   14,   14,
       16,  278,  278,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,  281,  282,  279,  283,  280,   22,   14,   14,  283,
       14,   14,   14,   60,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,  284,  282,  274,  274,  284,   14,   14,
      123,  123,   14,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,

       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,  274,  274,  182,  285,   14,   14,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,  274,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,    0,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274
    } ;

static const flex_int16_t yy_nxt[1474] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   17,   17,   17,   17,   17,    4,
       18,   19,    7,    7,    7,    7,   20,   21,    7,   22,
       23,   24,   25,   26,   27,   28,    7,   29,   30,   31,
       32,   33,   34,    7,   35,   36,   37,    7,   38,   39,
       40,   41,   42,   44,   44,   48,   49,   44,   44,   44,
       44,   44,   44,   43,  176,  215,  176,  215,   43,  183,
       45,   45,   46,   44,   44,   67,   45,   45,   45,   44,
       44,   69,   68,   45,   45,   45,  110,  183,   45,   71,
       45,   45,   45,   70,   45,   45,   45,   45,  174,   45,

      274,   72,   73,   43,   44,   44,   44,   44,  174,   43,
       44,   44,   44,   44,   44,   44,   43,   51,   52,   53,
       53,   53,   53,   53,   53,   46,   44,   44,   45,   83,
      174,   43,   44,   44,   84,   89,   45,   45,   45,  274,
      174,  274,   43,   45,   45,   45,   45,   90,   45,  100,
       43,   43,   91,   43,   45,   63,   45,   44,   44,   54,
       55,   55,   55,   55,   55,   55,   55,   56,   57,   57,
       57,   57,   57,   58,   58,  113,   85,   43,   86,   59,
       87,   60,   45,   92,   43,   43,   43,  115,   45,   59,
       45,   93,   45,   43,   88,   45,   99,  115,   45,   43,

       45,   45,  274,   45,  274,   60,   61,   61,   61,   61,
       61,   61,   61,   43,   45,   94,  113,   95,  108,   45,
       96,   45,   97,  182,   43,   45,   98,   45,  115,   45,
      109,   45,  117,   45,   45,  111,  183,  274,  115,  274,
       45,  274,   45,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,  183,  274,  125,  113,   45,   45,
       45,   45,   45,  274,   45,   64,  274,  274,  274,  115,
      274,   65,  128,   66,   74,  274,   75,   76,   45,  115,
       45,  274,  274,   77,   78,   79,  274,   80,  274,   81,
       82,  101,   45,  274,  102,  274,  103,  104,   45,   45,

       45,  274,  274,  105,  274,  106,  107,  112,  112,  112,
      112,  112,  112,  112,   45,   55,   55,   55,   55,   55,
       55,   55,   58,   58,   58,   58,   58,  274,   45,  274,
      274,   45,   45,  126,  127,   45,   45,   45,  130,   45,
       45,   45,  274,  132,   45,  129,  133,   45,   45,  131,
       45,  274,   45,  274,   45,  274,   45,  134,  274,   45,
       56,   61,   61,   61,   61,   61,   61,   61,   45,  135,
      274,  274,   59,   45,   45,   45,   45,   45,  274,   45,
      136,   45,   59,   45,   55,   55,   55,   55,   55,   55,
       55,   45,   45,  174,  274,  118,  137,   45,   45,   45,

       45,  138,  274,  174,  274,  118,   45,  119,  119,  119,
      119,  119,  119,  119,   45,  140,  274,   45,  118,  274,
       45,  274,   45,   45,  274,   45,  145,  274,  118,   56,
       58,   58,   58,   58,   58,   58,   58,  274,   45,   45,
      142,   59,   45,  274,   45,   45,   45,   45,   45,  274,
       45,   59,  120,  139,  121,   45,  122,  122,  122,  122,
      122,  122,  122,  123,  124,  124,  124,  124,  124,  124,
      124,   45,   45,  274,  124,  124,  274,   45,  150,   45,
       45,  124,  124,  124,  124,  124,  124,   61,   61,   61,
       61,   61,   61,   61,  146,   45,   45,  274,  274,   45,

       45,   45,   45,   45,   45,   45,  274,   45,   45,  141,
      274,  143,   45,  144,   45,  147,   45,  148,   45,   45,
       45,  113,   45,  149,   45,   45,   45,   45,   45,   45,
       45,  274,   45,  115,   45,   45,  274,   45,  274,   45,
       45,  153,  274,  115,  151,   45,   45,   45,   45,  274,
      152,   45,  155,  274,  154,   45,  157,   45,  158,   45,
      274,   45,   45,   45,   45,  156,   45,  159,   45,   45,
       45,  274,  274,   45,   45,   45,  274,   45,  161,   45,
       45,   45,   45,  160,   45,  162,  274,  274,  164,  274,
       45,  274,   45,   45,  165,  274,   45,  167,  163,   45,

       45,   45,   45,  169,   45,   45,   45,  166,   45,  168,
       45,   45,  274,   45,   45,  170,   45,  274,   45,   45,
       45,  274,   45,   45,  171,   45,   45,   45,  274,   45,
       45,   45,   45,  274,   45,  172,   45,  274,   45,  274,
      173,  178,  274,  179,   45,  180,  180,  180,  180,  180,
      180,  180,   45,  119,  119,  119,  119,  119,  119,  119,
       45,   45,  274,  184,  118,   45,   45,   45,   45,   45,
      185,   45,  274,   45,  118,   45,  122,  122,  122,  122,
      122,  122,  122,   45,  122,  122,  122,  122,  122,  122,
      122,   45,  181,  181,  181,  181,  181,  181,  181,  186,

       45,  274,  181,  181,  274,  274,   45,  274,   45,  181,
      181,  181,  181,  181,  181,   45,   45,  274,  274,   45,
      274,  187,   45,   45,   45,  189,   45,   45,  274,  188,
      192,  190,   45,  191,   45,  274,   45,   45,   45,  274,
       45,   45,  274,   45,  274,   45,   45,   45,   45,   45,
      193,  195,  274,   45,   45,  274,  274,  194,  274,  196,
       45,   45,   45,   45,   45,  274,  197,  274,   45,   45,
       45,   45,   45,  198,   45,  199,   45,  200,  274,   45,
       45,  201,  202,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,  204,  274,  274,  205,   45,

       45,   45,   45,  203,   45,   45,   45,  274,   45,   45,
      274,   45,   45,   45,   45,   45,  206,   45,   45,   45,
       45,  274,   45,   45,  274,   45,   45,   45,   45,   45,
       45,   45,   45,   45,   45,  274,   45,   45,  274,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,  274,
      274,   45,   45,   45,  274,   45,  207,   45,   45,   45,
       45,  208,   45,   45,  274,  274,   45,  274,   45,   45,
       45,   45,   45,  209,   45,   45,   45,  274,  274,  274,
       45,   45,   45,   45,   45,  212,  211,  210,   45,   45,
      274,   45,  274,   45,   45,   45,  274,   45,  213,   45,

       45,  274,   45,  274,  274,   45,  274,  221,  214,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,   45,  180,  180,  180,  180,  180,  180,
      180,   45,  180,  180,  180,  180,  180,  180,  180,  217,
      217,  217,  217,  217,  217,  217,  222,   45,  274,  217,
      217,  183,  274,   45,  274,   45,  217,  217,  217,  217,
      217,  217,  216,  216,  216,  216,  216,  216,  216,  183,
      218,  274,  219,   45,  220,  220,  220,  220,  220,  220,
      220,  223,  274,   45,   45,  225,  274,   45,   45,   45,
       45,   45,   45,   45,   45,   45,   45,   45,   45,  274,

      274,  224,   45,   45,  227,  226,   45,   45,   45,  274,
       45,   45,   45,   45,  274,   45,   45,   45,   45,   45,
       45,   45,   45,  274,   45,   45,  228,   45,   45,   45,
      274,   45,  274,   45,   45,   45,   45,  231,  229,   45,
       45,   45,  274,   45,   45,  230,   45,   45,   45,   45,
       45,  274,   45,   45,  233,  232,  274,   45,   45,   45,
       45,   45,   45,   45,   45,  234,   45,   45,  274,   45,
      274,   45,   45,   45,  274,   45,   45,  235,   45,   45,
       45,  274,   45,   45,   45,   45,   45,   45,  236,   45,
      274,   45,   45,  274,   45,  216,  216,  216,  216,  216,

      216,  216,   45,  220,  220,  220,  220,  220,  220,  220,
       45,  220,  220,  220,  220,  220,  220,  220,   45,  238,
      274,   45,   45,  274,   45,   45,   45,   45,   45,   45,
       45,   45,  240,   45,  239,   45,  274,  241,   45,  242,
      274,   45,   45,   45,   45,  274,   45,   45,   45,  274,
       45,  243,   45,   45,  274,   45,  274,  244,   45,  274,
       45,   45,  245,  274,   45,   45,  274,   45,  274,   45,
      246,   45,   45,   45,   45,  247,  274,   45,   45,  274,
       45,  274,   45,   45,   45,   45,   45,  248,   45,  274,
      274,  274,  274,  274,   45,  274,  249,  237,  237,  237,

      237,  237,  237,  237,   45,   45,  274,  274,   45,  274,
       45,   45,   45,   45,   45,  274,  251,   45,  252,  250,
       45,  274,  274,   45,  274,   45,   45,   45,   45,  253,
       45,   45,  274,   45,   45,   45,   45,   45,   45,   45,
       45,  254,   45,   45,   45,  255,  274,  274,   45,   45,
       45,   45,   45,  256,   45,   45,   45,  274,   45,   45,
      274,   45,  274,   45,   45,   45,   45,   45,  258,  274,
       45,   45,  257,  274,   45,  259,   45,   45,   45,   45,
       45,   45,   45,  274,   45,   45,  274,   45,   45,   45,
       45,  261,   45,   45,   45,  260,  262,   45,   45,  274,

      274,   45,  263,   45,   45,   45,   45,   45,  265,   45,
       45,   45,  274,  274,  274,  264,   45,   45,   45,   45,
      266,   45,   45,  274,  274,  274,   45,  267,   45,   45,
       45,  269,   45,   45,   45,  274,  268,  274,   45,   45,
      274,   45,   45,  274,   45,  270,   45,   45,   45,  274,
       45,   45,  272,   45,   45,   45,  271,   45,  274,   45,
       45,  274,   45,  274,  274,  274,  273,   45,  274,   45,
       45,   45,   45,   45,   45,   45,   47,  274,   47,   47,
       47,   47,   47,   50,   50,   50,   62,  274,   62,   62,
       62,   62,   62,   62,   62,  114,  114,  274,  114,  116,

      116,  274,  116,  112,  274,  112,  175,  274,  175,  177,
      177,  274,  177,  216,  216,  274,  216,  237,  237,    3,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274
    } ;

static const flex_int16_t yy_chk[1474] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,    7,   12,   12,    7,    7,    7,
        7,    7,    7,   12,  115,  174,  115,  174,  218,  181,
       23,   57,    7,    7,    7,   23,   23,   38,   23,    7,
        7,   24,   23,   38,   24,   38,   38,  181,   25,   25,
       24,   26,   24,   24,   25,   57,   25,   26,  112,   26,

       47,   25,   26,   46,    7,    7,   14,   14,  112,   44,
       14,   14,   14,   14,   14,   14,   42,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   28,   28,
      113,   41,   14,   14,   28,   30,   28,   31,   30,  120,
      113,  120,   21,   31,   30,   31,   30,   30,   35,   35,
      120,   20,   31,   19,   35,   18,   35,   14,   14,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   49,   29,   13,   29,   16,
       29,   16,   32,   32,   11,   10,    9,   49,   32,   16,
       32,   32,   34,    8,   29,   29,   34,   49,   34,    5,

       34,   29,  178,   29,  178,   16,   17,   17,   17,   17,
       17,   17,   17,  178,   33,   33,   50,   33,   37,   17,
       33,   37,   33,  124,    4,   39,   33,   37,   50,   37,
       37,   39,   54,   39,   40,   40,  124,    3,   50,    0,
       40,    0,   40,   17,   22,   22,   22,   22,   22,   22,
       22,   22,   45,   54,  124,    0,   64,  114,   45,   54,
       45,   54,   64,    0,   64,   22,    0,    0,    0,  114,
        0,   22,   66,   22,   27,    0,   27,   27,   66,  114,
       66,    0,    0,   27,   27,   27,    0,   27,    0,   27,
       27,   36,   68,    0,   36,    0,   36,   36,   68,   36,

       68,    0,    0,   36,    0,   36,   36,   48,   48,   48,
       48,   48,   48,   48,   51,   51,   51,   51,   51,   51,
       51,   51,   52,   52,   52,   52,   52,    0,   65,    0,
        0,   67,   69,   65,   65,   52,   65,   67,   69,   67,
       69,   70,    0,   71,   71,   67,   71,   70,   72,   70,
       71,    0,   71,    0,   72,    0,   72,   72,    0,   52,
       53,   53,   53,   53,   53,   53,   53,   53,   73,   74,
        0,    0,   53,   75,   73,   74,   73,   74,    0,   75,
       75,   75,   53,   55,   55,   55,   55,   55,   55,   55,
       55,   76,   77,  175,    0,   55,   76,   76,   77,   76,

       77,   77,    0,  175,    0,   55,   56,   56,   56,   56,
       56,   56,   56,   56,   79,   79,    0,   84,   56,    0,
       79,    0,   79,   84,    0,   84,   84,    0,   56,   58,
       58,   58,   58,   58,   58,   58,   58,    0,   78,   81,
       81,   58,   85,    0,   78,   81,   78,   81,   85,    0,
       85,   58,   59,   78,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   60,   60,   60,   60,   60,   60,   60,
       60,   87,   91,    0,   60,   60,    0,   87,   91,   87,
       91,   60,   60,   60,   60,   60,   60,   61,   61,   61,
       61,   61,   61,   61,   86,   80,   82,    0,    0,   83,

       61,   80,   82,   80,   82,   83,    0,   83,   88,   80,
        0,   82,   86,   83,   88,   88,   88,   89,   86,   89,
       86,  116,   92,   90,   61,   89,   90,   89,   92,   93,
       92,    0,   90,  116,   90,   93,    0,   93,    0,   94,
       95,   95,    0,  116,   93,   94,   95,   94,   95,    0,
       94,   96,   96,    0,   95,   97,   97,   96,   98,   96,
        0,   97,   99,   97,   98,   96,   98,   99,   99,  100,
       99,    0,    0,  101,  103,  100,    0,  100,  101,  101,
      103,  101,  103,  100,  102,  102,    0,    0,  103,    0,
      102,    0,  102,  104,  104,    0,  105,  105,  102,  104,

      106,  104,  105,  107,  105,  107,  106,  104,  106,  106,
      108,  107,    0,  107,  109,  108,  108,    0,  108,  110,
      109,    0,  109,  111,  110,  110,  117,  110,    0,  111,
      125,  111,  117,    0,  117,  111,  125,    0,  125,    0,
      111,  118,    0,  118,  118,  118,  118,  118,  118,  118,
      118,  118,  119,  119,  119,  119,  119,  119,  119,  119,
      126,  127,    0,  126,  119,  128,  126,  127,  126,  127,
      127,  128,    0,  128,  119,  121,  121,  121,  121,  121,
      121,  121,  121,  122,  122,  122,  122,  122,  122,  122,
      122,  123,  123,  123,  123,  123,  123,  123,  123,  129,

      129,    0,  123,  123,    0,    0,  129,    0,  129,  123,
      123,  123,  123,  123,  123,  130,  131,    0,    0,  132,
        0,  130,  131,  130,  131,  132,  133,  132,    0,  131,
      135,  133,  133,  134,  133,    0,  135,  134,  135,    0,
      136,  137,    0,  134,    0,  134,  136,  137,  136,  137,
      136,  138,    0,  139,  138,    0,    0,  137,    0,  139,
      138,  139,  138,  140,  141,    0,  140,    0,  142,  140,
      141,  140,  141,  141,  142,  142,  142,  143,    0,  143,
      144,  144,  145,  146,  145,  143,  144,  143,  144,  146,
      145,  146,  145,  147,  148,  148,    0,    0,  149,  147,

      148,  147,  148,  147,  149,  150,  149,    0,  151,  152,
        0,  150,  153,  150,  151,  152,  151,  152,  153,  154,
      153,    0,  155,  156,    0,  154,  157,  154,  155,  156,
      155,  156,  157,  158,  157,    0,  159,  160,    0,  158,
      161,  158,  159,  160,  159,  160,  161,  162,  161,    0,
        0,  163,  164,  162,    0,  162,  161,  163,  164,  163,
      164,  164,  165,  166,    0,    0,  167,    0,  165,  166,
      165,  166,  167,  167,  167,  168,  169,    0,    0,    0,
      170,  168,  169,  168,  169,  171,  170,  168,  170,  172,
        0,  171,    0,  171,  173,  172,    0,  172,  172,  184,

      173,    0,  173,    0,    0,  184,    0,  184,  173,  176,
      176,  176,  176,  176,  176,  176,  177,  177,  177,  177,
      177,  177,  177,  179,  179,  179,  179,  179,  179,  179,
      179,  180,  180,  180,  180,  180,  180,  180,  180,  182,
      182,  182,  182,  182,  182,  182,  185,  185,    0,  182,
      182,  182,    0,  185,    0,  185,  182,  182,  182,  182,
      182,  182,  215,  215,  215,  215,  215,  215,  215,  182,
      183,    0,  183,  183,  183,  183,  183,  183,  183,  183,
      183,  186,    0,  187,  186,  189,    0,  188,  189,  187,
      186,  187,  186,  188,  189,  188,  189,  190,  191,    0,

        0,  188,  192,  190,  191,  190,  191,  193,  192,    0,
      192,  194,  195,  193,    0,  193,  196,  194,  195,  194,
      195,  197,  196,    0,  196,  198,  195,  197,  199,  197,
        0,  198,    0,  198,  199,  200,  199,  202,  198,  201,
      202,  200,    0,  200,  203,  201,  202,  201,  202,  204,
      203,    0,  203,  205,  206,  204,    0,  204,  207,  205,
      206,  205,  206,  208,  207,  208,  207,  209,    0,  208,
        0,  208,  211,  209,    0,  209,  210,  210,  211,  212,
      211,    0,  210,  213,  210,  212,  214,  212,  213,  213,
        0,  213,  214,    0,  214,  216,  216,  216,  216,  216,

      216,  216,  219,  219,  219,  219,  219,  219,  219,  219,
      220,  220,  220,  220,  220,  220,  220,  220,  221,  222,
        0,  223,  222,    0,  221,  225,  221,  223,  222,  223,
      222,  225,  224,  225,  223,  224,    0,  225,  226,  226,
        0,  224,  227,  224,  226,    0,  226,  228,  227,    0,
      227,  227,  229,  228,    0,  228,    0,  229,  229,    0,
      229,  230,  230,    0,  231,  232,    0,  230,    0,  230,
      231,  232,  231,  232,  233,  233,    0,  234,  235,    0,
      233,    0,  233,  234,  235,  234,  235,  234,  236,    0,
        0,    0,    0,    0,  236,    0,  236,  237,  237,  237,

      237,  237,  237,  237,  238,  239,    0,    0,  240,    0,
      238,  239,  238,  239,  240,    0,  240,  241,  241,  239,
      242,    0,    0,  241,    0,  241,  242,  244,  242,  243,
      243,  246,    0,  244,  245,  244,  243,  246,  243,  246,
      245,  245,  245,  247,  248,  247,    0,    0,  249,  247,
      248,  247,  248,  249,  249,  250,  249,    0,  251,  252,
        0,  250,    0,  250,  251,  252,  251,  252,  253,    0,
      255,  253,  251,    0,  254,  254,  255,  253,  255,  253,
      254,  256,  254,    0,  257,  258,    0,  256,  259,  256,
      257,  258,  257,  258,  259,  256,  259,  260,  261,    0,

        0,  262,  260,  260,  261,  260,  261,  262,  263,  262,
      264,  263,    0,    0,    0,  262,  264,  263,  264,  263,
      264,  265,  266,    0,    0,    0,  267,  265,  266,  265,
      266,  267,  267,  268,  267,    0,  266,    0,  269,  268,
        0,  268,  270,    0,  269,  268,  269,  273,  270,    0,
      270,  271,  271,  273,  272,  273,  269,  271,    0,  271,
      272,    0,  272,    0,    0,    0,  272,  275,    0,  275,
      275,  275,  275,  275,  275,  275,  276,    0,  276,  276,
      276,  276,  276,  277,  277,  277,  278,    0,  278,  278,
      278,  278,  278,  278,  278,  279,  279,    0,  279,  280,

      280,    0,  280,  281,    0,  281,  282,    0,  282,  283,
      283,    0,  283,  284,  284,    0,  284,  285,  285,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  274,  274,  274,  274,
      274,  274,  274
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[80] =
    {   0,
0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "irlexer.l"
#line 2 "irlexer.l"

#include "../../include/ggc/irparser.hpp"
#include <cstdlib> // just for atoi, atof, strtol, strtof
#define YY_DECL yyy::parser::symbol_type yylex ()

#line 895 "irlexer.cpp"
#define YY_NO_INPUT 1
#line 897 "irlexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 12 "irlexer.l"


#line 1115 "irlexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 275 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1420 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 14 "irlexer.l"
{ /* ignore comments */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 15 "irlexer.l"
{ /* ignore whitespace */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "irlexer.l"
{ return yyy::parser::make_I_BLKID(yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "irlexer.l"
{ return yyy::parser::make_I_ID(yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "irlexer.l"
{ return yyy::parser::make_IRNUM_INT((int)atoi(yytext)); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "irlexer.l"
{ return yyy::parser::make_IRNUM_INT((int)strtol(yytext, NULL, 8)); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 22 "irlexer.l"
{ return yyy::parser::make_IRNUM_INT((int)strtol(yytext, NULL, 16)); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "irlexer.l"
{ return yyy::parser::make_IRNUM_FLOAT((float)atof(yytext)); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 25 "irlexer.l"
{ return yyy::parser::make_IRNUM_FLOAT((float)atof(yytext)); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 26 "irlexer.l"
{ return yyy::parser::make_IRNUM_FLOAT((float)strtof(yytext, NULL)); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 28 "irlexer.l"
{ return yyy::parser::make_I_RET(); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 29 "irlexer.l"
{ return yyy::parser::make_I_BR(); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "irlexer.l"
{ return yyy::parser::make_I_FNEG(); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 31 "irlexer.l"
{ return yyy::parser::make_I_ADD(); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 32 "irlexer.l"
{ return yyy::parser::make_I_FADD(); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 33 "irlexer.l"
{ return yyy::parser::make_I_SUB(); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 34 "irlexer.l"
{ return yyy::parser::make_I_FSUB(); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 35 "irlexer.l"
{ return yyy::parser::make_I_MUL(); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 36 "irlexer.l"
{ return yyy::parser::make_I_FMUL(); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 37 "irlexer.l"
{ return yyy::parser::make_I_DIV(); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 38 "irlexer.l"
{ return yyy::parser::make_I_FDIV(); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 39 "irlexer.l"
{ return yyy::parser::make_I_REM(); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 40 "irlexer.l"
{ return yyy::parser::make_I_FREM(); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 41 "irlexer.l"
{ return yyy::parser::make_I_AND(); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 42 "irlexer.l"
{ return yyy::parser::make_I_OR(); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 43 "irlexer.l"
{ return yyy::parser::make_I_ALLOCA(); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 44 "irlexer.l"
{ return yyy::parser::make_I_LOAD(); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 45 "irlexer.l"
{ return yyy::parser::make_I_STORE(); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 46 "irlexer.l"
{ return yyy::parser::make_I_GEP(); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 47 "irlexer.l"
{ return yyy::parser::make_I_FPTOSI(); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 48 "irlexer.l"
{ return yyy::parser::make_I_SITOFP(); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 49 "irlexer.l"
{ return yyy::parser::make_I_ZEXT(); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 50 "irlexer.l"
{ return yyy::parser::make_I_BITCAST(); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 51 "irlexer.l"
{ return yyy::parser::make_I_ICMP(); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 52 "irlexer.l"
{ return yyy::parser::make_I_FCMP(); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 53 "irlexer.l"
{ return yyy::parser::make_I_PHI(); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 54 "irlexer.l"
{ return yyy::parser::make_I_CALL(); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "irlexer.l"
{ return yyy::parser::make_I_DEFINE(); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "irlexer.l"
{ return yyy::parser::make_I_DECLARE(); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 58 "irlexer.l"
{ return yyy::parser::make_I_DSO_LOCAL(); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 59 "irlexer.l"
{ return yyy::parser::make_I_GLOBAL(); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 60 "irlexer.l"
{ return yyy::parser::make_I_CONSTANT(); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 61 "irlexer.l"
{ return yyy::parser::make_I_ALIGN(); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "irlexer.l"
{ return yyy::parser::make_I_NOUNDEF(); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 63 "irlexer.l"
{ return yyy::parser::make_I_LABEL(); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 64 "irlexer.l"
{ return yyy::parser::make_I_TAIL(); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 65 "irlexer.l"
{ return yyy::parser::make_I_TO(); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 67 "irlexer.l"
{ return yyy::parser::make_I_EQ(); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 68 "irlexer.l"
{ return yyy::parser::make_I_NE(); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 69 "irlexer.l"
{ return yyy::parser::make_I_SGT(); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 70 "irlexer.l"
{ return yyy::parser::make_I_SGE(); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 71 "irlexer.l"
{ return yyy::parser::make_I_SLT(); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 72 "irlexer.l"
{ return yyy::parser::make_I_SLE(); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "irlexer.l"
{ return yyy::parser::make_I_OEQ(); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "irlexer.l"
{ return yyy::parser::make_I_OGT(); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "irlexer.l"
{ return yyy::parser::make_I_OGE(); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "irlexer.l"
{ return yyy::parser::make_I_OLT(); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 "irlexer.l"
{ return yyy::parser::make_I_OLE(); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 "irlexer.l"
{ return yyy::parser::make_I_ONE(); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 80 "irlexer.l"
{ return yyy::parser::make_I_ORD(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 82 "irlexer.l"
{ return yyy::parser::make_I_I1(); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 83 "irlexer.l"
{ return yyy::parser::make_I_I8(); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 84 "irlexer.l"
{ return yyy::parser::make_I_I32(); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 85 "irlexer.l"
{ return yyy::parser::make_I_FLOAT(); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 86 "irlexer.l"
{ return yyy::parser::make_I_VOID(); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "irlexer.l"
{ return yyy::parser::make_I_STAR(); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "irlexer.l"
{ return yyy::parser::make_I_X(); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 90 "irlexer.l"
{ return yyy::parser::make_I_ZEROINITER(); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 91 "irlexer.l"
{ return yyy::parser::make_I_DOTDOTDOT(); /* VAArg */ }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 93 "irlexer.l"
{ return yyy::parser::make_I_LPAR(); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 94 "irlexer.l"
{ return yyy::parser::make_I_RPAR(); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 95 "irlexer.l"
{ return yyy::parser::make_I_LBRACKET(); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 96 "irlexer.l"
{ return yyy::parser::make_I_RBRACKET(); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 97 "irlexer.l"
{ return yyy::parser::make_I_LSQUARE(); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "irlexer.l"
{ return yyy::parser::make_I_RSQUARE(); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "irlexer.l"
{ return yyy::parser::make_I_COMMA(); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "irlexer.l"
{ return yyy::parser::make_I_EQUAL(); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 102 "irlexer.l"
{ std::cerr << "Unrecognized token: " << yytext << std::endl; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 103 "irlexer.l"
ECHO;
	YY_BREAK
#line 1578 "irlexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 275 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 275 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 274);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 103 "irlexer.l"


