name: Gnalc Compile Artifacts

permissions:
  contents: write

on:
  push:
    branches: [ "main", "ci", "iropt", "backendv3.0" ]
    paths:
      - 'lib/**'
      - 'include/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/compile_artifacts.yml'
  pull_request:
    branches: [ "main", "ci", "iropt", "backendv3.0" ]
    paths:
      - 'lib/**'
      - 'include/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/compile_artifacts.yml'

env:
  BUILD_TYPE: Release
  ARTIFACTS_BRANCH: "artifacts"
  TESTDATA_ZIP_URL: "https://github.com/caozhanhao/gnalc-test-data/releases/download/v1.0.0/testdata.zip"
  TESTDATA_DIR: "${{ github.workspace }}/testdata"
  ZIP_CACHE_DIR: "${{ github.workspace }}/testdata_cache"

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          persist-credentials: true    # ensure GITHUB_TOKEN is available for later pushes

      - name: Create Cache Directory
        run: mkdir -p ${{ env.ZIP_CACHE_DIR }}

      - name: Cache Test Data
        id: cache-zip
        uses: actions/cache@v3
        with:
          path: ${{ env.ZIP_CACHE_DIR }}/testdata.zip
          key: testcases-zip-v1.0.0
          restore-keys: testcases-zip-

      - name: Download Test Data Zip (if not cached)
        if: steps.cache-zip.outputs.cache-hit != 'true'
        run: |
          curl -L -o ${{ env.ZIP_CACHE_DIR }}/testdata.zip ${{ env.TESTDATA_ZIP_URL }}
          echo "Testdata zip downloaded from ${{ env.TESTDATA_ZIP_URL }}"

      - name: Extract testcases
        run: |
          mkdir -p ${{ env.TESTDATA_DIR }}
          unzip -q ${{ env.ZIP_CACHE_DIR }}/testdata.zip -d ${{ env.TESTDATA_DIR }}
          echo "Testcases extracted to ${{ env.TESTDATA_DIR }}"

      - name: Extract Branch Name
        id: branch-name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi

      - name: Configure CMake
        run: mkdir ${{github.workspace}}/build && cd ${{github.workspace}}/build && cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

      - name: Build Gnalc
        working-directory: ${{github.workspace}}/build
        run: make gnalc -j$(nproc)

      - name: Prepare Artifacts Directory
        run: |
          mkdir -p artifacts
          echo "ARTIFACTS_DIR=$(pwd)/artifacts" >> $GITHUB_ENV

      # TODO: COMPILE_OPTIONS
      - name: Set Compile Options
        id: set-options
        run: |
          if [ "${{ github.ref_name }}" == "iropt" ]; then
            echo "COMPILE_OPTIONS=-O1" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "backendv3.0" ]; then
            echo "COMPILE_OPTIONS=-O1" >> $GITHUB_ENV
          else
            echo "COMPILE_OPTIONS=-O1" >> $GITHUB_ENV
          fi

      - name: Compile Testcases
        env:
          BRANCH_NAME: ${{ steps.branch-name.outputs.branch }}
        run: |
          base_path="${{ env.TESTDATA_DIR }}"
          find "$base_path" -type f -name "*.sy" | while read testcase; do
            rel_path="${testcase#$base_path/}"
            dir_path=$(dirname "$rel_path")
            test_name=$(basename "$testcase" .sy)
            test_id="${dir_path//\//_}_${test_name}"

            mkdir -p "$ARTIFACTS_DIR/$BRANCH_NAME/llvm/$dir_path"
            mkdir -p "$ARTIFACTS_DIR/$BRANCH_NAME/aarch64/$dir_path"

            ./build/gnalc --log none -S "$testcase" -emit-llvm \
              -o "$ARTIFACTS_DIR/$BRANCH_NAME/llvm/$dir_path/$test_id.ll" \
              ${{ env.COMPILE_OPTIONS }}

            ./build/gnalc --log none -S "$testcase" \
              -o "$ARTIFACTS_DIR/$BRANCH_NAME/aarch64/$dir_path/$test_id.s" \
              ${{ env.COMPILE_OPTIONS }}
          done

      - name: Checkout Artifacts Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.ARTIFACTS_BRANCH }}
          path: artifacts-branch
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Update Artifacts Branch
        run: |
          find artifacts-branch -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          
          cp -R ${{ env.ARTIFACTS_DIR }}/* artifacts-branch/
          
          cd artifacts-branch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update artifacts from ${{ github.sha }}"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin ${{ env.ARTIFACTS_BRANCH }} 
          fi