name: Gnalc Compile Artifacts

on:
  push:
    branches: [ "main", "ci", "iropt", "backendv3.0" ]
    paths:
      - 'lib/**'
      - 'include/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/compile_artifacts.yml'
  pull_request:
    branches: [ "main", "ci", "iropt", "backendv3.0" ]
    paths:
      - 'lib/**'
      - 'include/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/compile_artifacts.yml'

env:
  BUILD_TYPE: Release
  ARTIFACTS_BRANCH: "artifacts"
  TESTDATA_ZIP_REPO: "https://e.coding.net/caozhanhao/gnalc-test-data/zip.git"
  TESTDATA_DIR: "${{ github.workspace }}/testdata"
  ZIP_CACHE_DIR: "${{ github.workspace }}/testdata_cache"

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Create Cache Directory
        run: mkdir -p ${{ env.TESTDATA_CACHE_DIR }}

      - name: Cache Test Data
        id: cache-zip
        uses: actions/cache@v3
        with:
          path: ${{ env.ZIP_CACHE_DIR }}
          key: testcases-zip-${{ hashFiles('.github/testcases_version.txt') }}
          restore-keys: testcases-zip-

      - name: Clone testdata repository (if not cached)
        if: steps.cache-zip.outputs.cache-hit != 'true'
        run: |
          git clone --depth 1 ${{ env.TESTCASE_REPO }} testdata-repo
          cp testdata-repo/testdata.zip ${{ env.ZIP_CACHE_DIR }}/
          cd testdata-repo
          git rev-parse HEAD > ../.github/testcases_version.txt
          echo "Testdata updated to $(cat ../.github/testcases_version.txt)"

      - name: Extract branch name
        id: branch-name
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          fi

      - name: Configure CMake
        run: mkdir ${{github.workspace}}/build && cd ${{github.workspace}}/build && cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..

      - name: Build Gnalc
        working-directory: ${{github.workspace}}/build
        run: make gnalc -j$(nproc)

      - name: Prepare artifacts directory
        run: |
          mkdir -p artifacts
          echo "ARTIFACTS_DIR=$(pwd)/artifacts" >> $GITHUB_ENV

      - name: Compile test cases
        env:
          BRANCH_NAME: ${{ steps.branch-name.outputs.branch }}
#          TODO: COMPILE_OPTIONS
          COMPILE_OPTIONS: >
            ${{ 
              github.ref_name == 'iropt' && '-O1' || 
              github.ref_name == 'backendv3.0' && '-O1' || 
              '-O1'
            }}
        run: |
          base_path="${{ env.TESTDATA_DIR }}"
          find "$base_path" -type f -name "*.sy" | while read testcase; do
            rel_path="${testcase#$base_path/}"
            dir_path=$(dirname "$rel_path")
            test_name=$(basename "$testcase" .sy)
            test_id="${dir_path//\//_}_${test_name}"

            mkdir -p "$ARTIFACTS_DIR/llvm/$BRANCH_NAME/$dir_path"
            mkdir -p "$ARTIFACTS_DIR/aarch64/$BRANCH_NAME/$dir_path"

            ./build/gnalc -S "$testcase" -emit-llvm \
              -o "$ARTIFACTS_DIR/llvm/$BRANCH_NAME/$dir_path/$test_id.ll" \
              $COMPILE_OPTIONS

            ./build/gnalc -S "$testcase" \
              -o "$ARTIFACTS_DIR/aarch64/$BRANCH_NAME/$dir_path/$test_id.s" \
              $COMPILE_OPTIONS
          done

      - name: Checkout artifacts branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.ARTIFACTS_BRANCH }}
          path: artifacts-branch

      - name: Update artifacts branch
        env:
          SSHK: ${{ secrets.GH_PAT }}
        run: |
          find artifacts-branch -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          
          cp -R ${{ env.ARTIFACTS_DIR }}/* artifacts-branch/
          
          cd artifacts-branch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update artifacts from ${{ github.sha }}"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin ${{ env.ARTIFACTS_BRANCH }} 
          fi