name: Gnalc Compile Artifacts

permissions:
  contents: write

on:
  push:
    branches: [ "main", "ci", "iropt", "backendv3.0" ]
    paths:
      - 'lib/**'
      - 'include/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/compile_artifacts.yml'
  pull_request:
    branches: [ "main", "ci", "iropt", "backendv3.0" ]
    paths:
      - 'lib/**'
      - 'include/**'
      - 'test/**'
      - 'CMakeLists.txt'
      - '.github/workflows/compile_artifacts.yml'

env:
  BUILD_TYPE: Release
  ARTIFACTS_BRANCH: "artifacts"
  TESTDATA_ZIP_URL: "https://github.com/caozhanhao/gnalc-test-data/releases/download/v1.0.0/testdata.zip"
  TESTDATA_DIR: "${{ github.workspace }}/testdata"
  ZIP_CACHE_DIR: "${{ github.workspace }}/testdata_cache"

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Artifacts Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.ARTIFACTS_BRANCH }}
          path: artifacts-branch
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Compare Commit SHA
        id: check
        run: |
          LAST=$(cat artifacts-branch/last_run.txt 2>/dev/null || echo "")
          echo "Previous run was on: $LAST"
          echo "::set-output name=previous::$LAST"
          echo "::set-output name=current::${GITHUB_SHA}"

      - name: Skip if already ran on this commit
        if: steps.check.outputs.previous == steps.check.outputs.current
        run: |
          echo "This commit (${GITHUB_SHA}) has already been processed."
          exit 0

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Create Cache Directory
        run: mkdir -p ${{ env.ZIP_CACHE_DIR }}

      - name: Cache Test Data
        id: cache-zip
        uses: actions/cache@v3
        with:
          path: ${{ env.ZIP_CACHE_DIR }}/testdata.zip
          key: testcases-zip-v1.0.0
          restore-keys: testcases-zip-

      - name: Download Test Data Zip (if not cached)
        if: steps.cache-zip.outputs.cache-hit != 'true'
        run: |
          curl -L -o ${{ env.ZIP_CACHE_DIR }}/testdata.zip ${{ env.TESTDATA_ZIP_URL }}

      - name: Extract testcases
        run: |
          mkdir -p ${{ env.TESTDATA_DIR }}
          unzip -q ${{ env.ZIP_CACHE_DIR }}/testdata.zip -d ${{ env.TESTDATA_DIR }}

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} ..

      - name: Build Gnalc
        run: make -C build gnalc -j$(nproc)

      - name: Prepare Artifacts Directory
        run: |
          mkdir -p artifacts
          echo "ARTIFACTS_DIR=$(pwd)/artifacts" >> $GITHUB_ENV

      # TODO: COMPILE_OPTIONS
      - name: Set Compile Options
        id: set-options
        run: echo "COMPILE_OPTIONS=-O1" >> $GITHUB_ENV

      - name: Compile Testcases
        run: |
          base_path="${{ env.TESTDATA_DIR }}"
          find "$base_path" -type f -name "*.sy" | while read testcase; do
            rel_path="${testcase#$base_path/}"
            dir_path=$(dirname "$rel_path")
            test_name=$(basename "$testcase" .sy)

            mkdir -p "$ARTIFACTS_DIR/artifacts/llvm/$dir_path"
            mkdir -p "$ARTIFACTS_DIR/artifacts/aarch64/$dir_path"

            ./build/gnalc --log none -S "$testcase" -emit-llvm \
              -o "$ARTIFACTS_DIR/artifacts/llvm/$dir_path/$test_name.ll" \
              ${{ env.COMPILE_OPTIONS }}

            ./build/gnalc --log none -S "$testcase" \
              -o "$ARTIFACTS_DIR/artifacts/aarch64/$dir_path/$test_name.s" \
              ${{ env.COMPILE_OPTIONS }}
          done

      - name: Checkout artifacts branch for update
        uses: actions/checkout@v4
        with:
          ref: ${{ env.ARTIFACTS_BRANCH }}
          path: artifacts-branch
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Clean out old artifacts
        run: |
          rm -rf artifacts-branch/*

      - name: Copy new artifacts
        run: |
          cp -R artifacts/* artifacts-branch/

      - name: Generate metadata files
        run: |
          TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          cat > artifacts-branch/README.md <<EOF
          # Gnalc Artifacts

          - **Branch:** ${{ github.ref_name }}
          - **Generated at:** $TS (UTC)
          - **Commit SHA:** ${{ github.sha }}

          Artifacts built by GitHub Actions.  
          EOF

          echo "${{ github.sha }}" > artifacts-branch/last_run.txt

      - name: Commit & Push updates
        run: |
          cd artifacts-branch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md last_run.txt artifacts/
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update artifacts from ${{ github.sha }}"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git push origin ${{ env.ARTIFACTS_BRANCH }} 
          fi